import { describe, it, expect } from 'vitest';
import { generateBom, getSkus } from './bomEngine';
import { consolidateSimpleDeviceRows } from './bom/consolidateSimpleDevices';
import { buildProjectWideOpticBom } from './bom/opticPacks';
import {
  createQuoteItemsFromBom,
  calculateQuoteSummary,
  DEFAULT_DISCOUNT_CONFIG,
  type DiscountCategoryConfig,
} from './pricingEngine';
import { skuService } from '../services/skuService';

describe('BOM to Quotation Engine Validation & Arithmetic Integrity', () => {
  const mockNodes = [
    {
      id: 'node-ta25e-1',
      type: 'hardwareNode',
      position: { x: 100, y: 100 },
      data: {
        label: 'GigaVUE-TA25E #1',
        configType: 'Hardware',
        model: 'GigaVUE-TA25E',
        sku: 'TA25E-BASE',
        site: 'Site Nuuk',
      },
    },
    {
      id: 'node-ta25e-2',
      type: 'hardwareNode',
      position: { x: 100, y: 300 },
      data: {
        label: 'GigaVUE-TA25E #2',
        configType: 'Hardware',
        model: 'GigaVUE-TA25E',
        sku: 'TA25E-BASE',
        site: 'Site Nuuk',
      },
    },
    {
      id: 'node-hc3-1',
      type: 'hardwareNode',
      position: { x: 500, y: 200 },
      data: {
        label: 'GigaVUE-HC3 Nuuk',
        configType: 'Hardware',
        model: 'GigaVUE-HC3',
        sku: 'HC3-BASE',
        site: 'Site Nuuk',
      },
    },
  ];

  const mockEdges = [
    {
      id: 'edge-1',
      source: 'node-ta25e-1',
      target: 'node-hc3-1',
    },
    {
      id: 'edge-2',
      source: 'node-ta25e-2',
      target: 'node-hc3-1',
    },
  ];

  it('verifies that every SKU generated by the BOM exists in the SKU catalog and has non-zero pricing', () => {
    const rawBom = consolidateSimpleDeviceRows(
      generateBom(mockNodes, mockEdges, 'HTL', '36', 'EU', true, {}),
    );
    const masterBom = buildProjectWideOpticBom(rawBom, getSkus());

    expect(masterBom.length).toBeGreaterThan(0);

    const quoteItems = createQuoteItemsFromBom(masterBom, 36);
    expect(quoteItems.length).toBe(masterBom.length);

    for (const item of quoteItems) {
      expect(item.sku).toBeTruthy();
      expect(item.qty).toBeGreaterThan(0);
      expect(Number.isFinite(item.unitListPrice)).toBe(true);
      expect(item.unitListPrice).toBeGreaterThan(0);

      expect(['Software', 'Chassis', 'Module', 'Optic', 'TAP', 'Support', 'Accessory', 'Other']).toContain(
        item.category,
      );
    }
  });

  it('verifies exact mathematical calculation for term software licenses and discounts', () => {
    const rawBom = consolidateSimpleDeviceRows(
      generateBom(mockNodes, mockEdges, 'HTL', '36', 'EU', true, {}),
    );
    const masterBom = buildProjectWideOpticBom(rawBom, getSkus());
    const quoteItems = createQuoteItemsFromBom(masterBom, 36);

    const discountConfig: DiscountCategoryConfig = {
      ...DEFAULT_DISCOUNT_CONFIG,
      software: 35,
      chassis: 20,
    };

    const summary = calculateQuoteSummary(quoteItems, discountConfig, false, false, false);

    expect(summary.items.length).toBe(quoteItems.length);
    expect(summary.totalListPrice).toBeGreaterThan(0);
    expect(summary.totalNetPrice).toBeGreaterThan(0);
    expect(summary.totalDiscountAmount).toBeGreaterThan(0);

    const calculatedNet = summary.totalListPrice - summary.totalDiscountAmount;
    expect(Math.abs(summary.totalNetPrice - calculatedNet)).toBeLessThan(0.01);

    let manualListSum = 0;
    let manualNetSum = 0;

    for (const item of summary.items) {
      const termMult = item.isMonthlyPrice && item.termMonths ? item.termMonths : 1;
      const expectedExtList = item.qty * item.unitListPrice * termMult;
      const expectedExtNet = expectedExtList * (1 - item.effectiveDiscountPercent / 100);

      expect(Math.abs(item.extendedListPrice - expectedExtList)).toBeLessThan(0.01);
      expect(Math.abs(item.extendedNetPrice - expectedExtNet)).toBeLessThan(0.01);

      manualListSum += item.extendedListPrice;
      manualNetSum += item.extendedNetPrice;
    }

    expect(Math.abs(summary.totalListPrice - manualListSum)).toBeLessThan(0.01);
    expect(Math.abs(summary.totalNetPrice - manualNetSum)).toBeLessThan(0.01);
  });

  it('verifies standard catalog reference prices for HC3 and TA series SKUs', () => {
    expect(skuService.getSKUByPartNumber('GVS-HC3A1-HW')?.listPrice).toBe(22645);
    expect(skuService.getSKUByPartNumber('GVS-HC3A0-SW-TM')?.listPriceMonthly).toBe(2365);
    expect(skuService.getSKUByPartNumber('PRT-HC3-X24-HW')?.listPrice).toBe(3165);
    expect(skuService.getSKUByPartNumber('PRT-HC3-X24-SW-TM')?.listPriceMonthly).toBe(2155);
    expect(skuService.getSKUByPartNumber('SMT-HC3-C08-HW')?.listPrice).toBe(24400);
    expect(skuService.getSKUByPartNumber('SMT-HC3-C08-SW-TM')?.listPriceMonthly).toBe(3530);
    expect(skuService.getSKUByPartNumber('SMT-HC3-GEN3-FVU-SW-TM')?.listPriceMonthly).toBe(2145);
    expect(skuService.getSKUByPartNumber('SMT-HC3-GEN3-GTPMAX-SW-TM')?.listPriceMonthly).toBe(4260);
    expect(skuService.getSKUByPartNumber('GVS-TAX20E-SW-TM')?.listPriceMonthly).toBe(1205);
  });
});
